### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by mahsasanaei-ai** [Sohaib9920/Media_Downloader_and_Summarizer#1]
Hello. Some items from the requirements file seem not to be installed and need to be installed manually, and as far as I have checked, there is no tkinter in that file.

**Comment by Sohaib9920** [comment]
Thank you for opening this issue and your valuable contribution. tkinter is part of the Python standard library and doesn't need to be in `requirements.txt`. I've updated `requirements.txt` to reflect the other dependencies from my virtual environment.
